### ISSUE TITLE
Quadro extra

### ISSUE THREAD

**Issue by igorknop** [ufjf-dcc104/dcc138-2020-3ere-atv3-rgoulart8#1]
Confere pois acho que está com um quadro a mais (o qmax é 7). Isso faz a animação "piscar"

**Comment by rgoulart8** [comment]
Corrigido em commit/80094a8f65c3c82e8cf39723a3ed9ff619c16115

**Comment by igorknop** [comment]
Corrigido em 80094a8f65c3c82e8cf39723a3ed9ff619c16115
